DROP TABLE "GOODS_SELL";

CREATE TABLE "GOODS_SELL" (
	"GOODS_NO"	NUMBER		NOT NULL,
	"SELLER_NO"	NUMBER		NOT NULL,
	"BUYER_NO"	NUMBER		NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"SELL_PRICE"	NUMBER	DEFAULT 0	NOT NULL,
	"VIEW_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"DESCRIPTION"	VARCHAR2(4000)		NULL,
	"REFRESHED_AT"	DATE	DEFAULT SYSDATE	NULL,
	"CREATED_AT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"GOODS_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"SELL_STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "GOODS_SELL"."GOODS_NO" IS '판매글번호';

COMMENT ON COLUMN "GOODS_SELL"."SELLER_NO" IS '판매자';

COMMENT ON COLUMN "GOODS_SELL"."BUYER_NO" IS '구매자';

COMMENT ON COLUMN "GOODS_SELL"."CATEGORY_NO" IS '카테고리';

COMMENT ON COLUMN "GOODS_SELL"."TITLE" IS '제목';

COMMENT ON COLUMN "GOODS_SELL"."SELL_PRICE" IS '판매금액';

COMMENT ON COLUMN "GOODS_SELL"."VIEW_COUNT" IS '조회수';

COMMENT ON COLUMN "GOODS_SELL"."DESCRIPTION" IS '상품설명';

COMMENT ON COLUMN "GOODS_SELL"."REFRESHED_AT" IS '끌올시간';

COMMENT ON COLUMN "GOODS_SELL"."CREATED_AT" IS '등록시간';

COMMENT ON COLUMN "GOODS_SELL"."GOODS_DEL_FL" IS '삭제여부';

COMMENT ON COLUMN "GOODS_SELL"."SELL_STATUS" IS '판매상태';

DROP TABLE "GOODS_IMAGE";

CREATE TABLE "GOODS_IMAGE" (
	"IMAGE_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NOT NULL,
	"IMAGE_PATH"	VARCHAR2(300)		NOT NULL
);

COMMENT ON COLUMN "GOODS_IMAGE"."IMAGE_NO" IS '사진번호';

COMMENT ON COLUMN "GOODS_IMAGE"."GOODS_NO" IS '판매글번호';

COMMENT ON COLUMN "GOODS_IMAGE"."IMAGE_PATH" IS '경로';

DROP TABLE "CATEGORY";

CREATE TABLE "CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NO" IS '카테고리번호';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NAME" IS '카테고리이름';

DROP TABLE "CHAT_MESSAGE";

CREATE TABLE "CHAT_MESSAGE" (
	"MESSAGE_NO"	NUMBER		NOT NULL,
	"CHAT_NO"	NUMBER		NOT NULL,
	"SENDER_NO"	NUMBER		NOT NULL,
	"MESSAGE"	VARCHAR2(4000)		NOT NULL,
	"READ_OR_NOT"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"M_CREATED_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "CHAT_MESSAGE"."MESSAGE_NO" IS '메세지번호';

COMMENT ON COLUMN "CHAT_MESSAGE"."CHAT_NO" IS '채팅방번호';

COMMENT ON COLUMN "CHAT_MESSAGE"."SENDER_NO" IS '보낸사람번호';

COMMENT ON COLUMN "CHAT_MESSAGE"."MESSAGE" IS '메세지';

COMMENT ON COLUMN "CHAT_MESSAGE"."READ_OR_NOT" IS '읽음확인';

COMMENT ON COLUMN "CHAT_MESSAGE"."M_CREATED_AT" IS '작성일';

DROP TABLE "GU_AREA";

CREATE TABLE "GU_AREA" (
	"GU_NO"	NUMBER		NOT NULL,
	"GU_NAME"	VARCHAR2(15)		NOT NULL
);

COMMENT ON COLUMN "GU_AREA"."GU_NO" IS '구번호';

COMMENT ON COLUMN "GU_AREA"."GU_NAME" IS '구 이름';

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(20)		NOT NULL,
	"MEMBER_NICKNAME"	VARCHAR2(30)		NOT NULL,
	"INTRODUCE"	VARCHAR2(2000)		NULL,
	"MEMBER_TEL"	CHAR(11)		NOT NULL,
	"MEMBER_ADDRESS"	VARCHAR2(300)		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(300)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	CHAR(1)	DEFAULT 1	NOT NULL,
	"BLOCK_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BIRTHDAY"	CHAR(8)		NOT NULL,
	"MANNER"	NUMBER	DEFAULT 36.5	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일(아이디)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '닉네임';

COMMENT ON COLUMN "MEMBER"."INTRODUCE" IS '자기소개';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '권한';

COMMENT ON COLUMN "MEMBER"."BLOCK_FL" IS '아이디정지여부';

COMMENT ON COLUMN "MEMBER"."BIRTHDAY" IS '생년월일';

COMMENT ON COLUMN "MEMBER"."MANNER" IS '매너온도';

DROP TABLE "REVIEW";

CREATE TABLE "REVIEW" (
	"RATING_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NOT NULL,
	"RECEIVER_NO"	NUMBER		NOT NULL,
	"MESSAGE"	VARCHAR2(3000)		NULL,
	"CREATED_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "REVIEW"."RATING_NO" IS '거래후기 번호';

COMMENT ON COLUMN "REVIEW"."MEMBER_NO" IS '작성자';

COMMENT ON COLUMN "REVIEW"."GOODS_NO" IS '판매글번호';

COMMENT ON COLUMN "REVIEW"."RECEIVER_NO" IS '후기 받은 사람';

COMMENT ON COLUMN "REVIEW"."MESSAGE" IS '거래후기글';

COMMENT ON COLUMN "REVIEW"."CREATED_AT" IS '작성일';

DROP TABLE "CHAT_ROOM";

CREATE TABLE "CHAT_ROOM" (
	"CHAT_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NOT NULL,
	"BUYER_NO"	NUMBER		NOT NULL,
	"R_CREATED_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "CHAT_ROOM"."CHAT_NO" IS '채팅방번호';

COMMENT ON COLUMN "CHAT_ROOM"."GOODS_NO" IS '판매글번호';

COMMENT ON COLUMN "CHAT_ROOM"."BUYER_NO" IS '구매자번호';

COMMENT ON COLUMN "CHAT_ROOM"."R_CREATED_AT" IS '작성일';

DROP TABLE "REVIEW_RATING";

CREATE TABLE "REVIEW_RATING" (
	"REVIEW_NO"	NUMBER		NOT NULL,
	"MANNER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REVIEW_RATING"."REVIEW_NO" IS '거래후기 번호';

COMMENT ON COLUMN "REVIEW_RATING"."MANNER_NO" IS '매너번호';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"B_CREATED_AT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"B_REFRESHED_AT"	DATE	DEFAULT SYSDATE	NULL,
	"VIEW_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판 코드';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '내용';

COMMENT ON COLUMN "BOARD"."B_CREATED_AT" IS '작성일';

COMMENT ON COLUMN "BOARD"."B_REFRESHED_AT" IS '마지막수정일';

COMMENT ON COLUMN "BOARD"."VIEW_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '삭제여부';

DROP TABLE "BOARD_TYPE";

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판 코드';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판 이름';

DROP TABLE "BOARD_IMG";

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(300)		NOT NULL,
	"IMG_RENAME"	VARCHAR2(30)		NOT NULL,
	"IMG_ORIGINAL"	VARCHAR2(300)		NOT NULL,
	"IMG_ORDER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지 번호';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "BOARD_IMG"."IMG_PATH" IS '경로';

COMMENT ON COLUMN "BOARD_IMG"."IMG_RENAME" IS '변경명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIGINAL" IS '원본명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORDER" IS '순서';

DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"C_CREATED_AT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '답변번호';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '작성자';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '내용';

COMMENT ON COLUMN "COMMENT"."C_CREATED_AT" IS '작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '삭제여부';

DROP TABLE "USER_COMPLAIN";

CREATE TABLE "USER_COMPLAIN" (
	"U_COMPLAIN_NO"	NUMBER		NOT NULL,
	"U_COM1_CTG_NO"	NUMBER		NOT NULL,
	"U_COM2_CTG_NO"	NUMBER		NOT NULL,
	"U_COMPLAINER"	NUMBER		NOT NULL,
	"U_COMPLAINED"	NUMBER		NOT NULL,
	"U_COM_CONTENT"	VARCHAR2(4000)		NULL,
	"U_COM_CREATED_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "USER_COMPLAIN"."U_COMPLAIN_NO" IS '유저신고글 번호';

COMMENT ON COLUMN "USER_COMPLAIN"."U_COM1_CTG_NO" IS '신고카테고리1번호';

COMMENT ON COLUMN "USER_COMPLAIN"."U_COM2_CTG_NO" IS '신고카테고리2 번호';

COMMENT ON COLUMN "USER_COMPLAIN"."U_COMPLAINER" IS '신고한 사람';

COMMENT ON COLUMN "USER_COMPLAIN"."U_COMPLAINED" IS '신고당한 사람';

COMMENT ON COLUMN "USER_COMPLAIN"."U_COM_CONTENT" IS '신고내용';

COMMENT ON COLUMN "USER_COMPLAIN"."U_COM_CREATED_AT" IS '작성일';

DROP TABLE "U_COMPLAIN_CTG_1";

CREATE TABLE "U_COMPLAIN_CTG_1" (
	"U_COM1_CTG_NO"	NUMBER		NOT NULL,
	"U_COM1_COMMENT"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "U_COMPLAIN_CTG_1"."U_COM1_CTG_NO" IS '신고카테고리1번호';

COMMENT ON COLUMN "U_COMPLAIN_CTG_1"."U_COM1_COMMENT" IS '카테고리1내용';

DROP TABLE "U_COMPLAIN_CTG_2";

CREATE TABLE "U_COMPLAIN_CTG_2" (
	"U_COM2_CTG_NO"	NUMBER		NOT NULL,
	"U_COM1_CTG_NO"	NUMBER		NOT NULL,
	"U_COM2_COMMENT"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "U_COMPLAIN_CTG_2"."U_COM2_CTG_NO" IS '신고카테고리2 번호';

COMMENT ON COLUMN "U_COMPLAIN_CTG_2"."U_COM1_CTG_NO" IS '신고카테고리1 번호';

COMMENT ON COLUMN "U_COMPLAIN_CTG_2"."U_COM2_COMMENT" IS '카테고리2내용';

DROP TABLE "BOARD_COMPLAIN";

CREATE TABLE "BOARD_COMPLAIN" (
	"B_COMPLAIN_NO"	NUMBER		NOT NULL,
	"B_COMPLAINER"	NUMBER		NOT NULL,
	"B_COMPLAINED"	NUMBER		NOT NULL,
	"B_COM1_CTG_NO"	NUMBER		NOT NULL,
	"B_COM2_CTG_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NOT NULL,
	"B_COM_CONTENT"	VARCHAR2(4000)		NULL,
	"B_COM_CREATED_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "BOARD_COMPLAIN"."B_COMPLAIN_NO" IS '유저신고글 번호';

COMMENT ON COLUMN "BOARD_COMPLAIN"."B_COMPLAINER" IS '신고한 사람';

COMMENT ON COLUMN "BOARD_COMPLAIN"."B_COMPLAINED" IS '신고당한 사람';

COMMENT ON COLUMN "BOARD_COMPLAIN"."B_COM1_CTG_NO" IS '신고카테고리1번호';

COMMENT ON COLUMN "BOARD_COMPLAIN"."B_COM2_CTG_NO" IS '신고카테고리2 번호';

COMMENT ON COLUMN "BOARD_COMPLAIN"."GOODS_NO" IS '판매글번호';

COMMENT ON COLUMN "BOARD_COMPLAIN"."B_COM_CONTENT" IS '신고내용';

COMMENT ON COLUMN "BOARD_COMPLAIN"."B_COM_CREATED_AT" IS '작성일';

DROP TABLE "B_COMPLAIN_CTG_1";

CREATE TABLE "B_COMPLAIN_CTG_1" (
	"B_COM1_CTG_NO"	NUMBER		NOT NULL,
	"B_COM1_COMMENT"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "B_COMPLAIN_CTG_1"."B_COM1_CTG_NO" IS '신고카테고리1번호';

COMMENT ON COLUMN "B_COMPLAIN_CTG_1"."B_COM1_COMMENT" IS '카테고리1내용';

DROP TABLE "B_COMPLAIN_CTG_2";

CREATE TABLE "B_COMPLAIN_CTG_2" (
	"B_COM2_CTG_NO"	NUMBER		NOT NULL,
	"B_COM1_CTG_NO"	NUMBER		NOT NULL,
	"B_COM2_COMMENT"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "B_COMPLAIN_CTG_2"."B_COM2_CTG_NO" IS '신고카테고리2 번호';

COMMENT ON COLUMN "B_COMPLAIN_CTG_2"."B_COM1_CTG_NO" IS '신고카테고리1번호';

COMMENT ON COLUMN "B_COMPLAIN_CTG_2"."B_COM2_COMMENT" IS '카테고리2내용';

DROP TABLE "GOODS_LIKE";

CREATE TABLE "GOODS_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NOT NULL,
	"LIKE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "GOODS_LIKE"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "GOODS_LIKE"."GOODS_NO" IS '판매글번호';

COMMENT ON COLUMN "GOODS_LIKE"."LIKE_TIME" IS '찜한 시간';

DROP TABLE "REQUEST_PAY";

CREATE TABLE "REQUEST_PAY" (
	"ORDER_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NULL,
	"TRADER_NO"	NUMBER		NOT NULL,
	"ORDER_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USE_POINT"	NUMBER		NOT NULL,
	"BUY_STATUS"	NUMBER		NOT NULL,
	"REMAIN_POINT"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "REQUEST_PAY"."ORDER_NO" IS '주문번호';

COMMENT ON COLUMN "REQUEST_PAY"."GOODS_NO" IS '판매글번호';

COMMENT ON COLUMN "REQUEST_PAY"."TRADER_NO" IS '회원번호';

COMMENT ON COLUMN "REQUEST_PAY"."ORDER_DATE" IS '결제시간';

COMMENT ON COLUMN "REQUEST_PAY"."USE_POINT" IS '이용한 바나나페이';

COMMENT ON COLUMN "REQUEST_PAY"."BUY_STATUS" IS '상태';

COMMENT ON COLUMN "REQUEST_PAY"."REMAIN_POINT" IS '잔여 바나나페이';

DROP TABLE "USER_BLOCK";

CREATE TABLE "USER_BLOCK" (
	"USER_BLOCKED"	NUMBER		NOT NULL,
	"USER_BLOCKER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "USER_BLOCK"."USER_BLOCKED" IS '차단당한 사람';

COMMENT ON COLUMN "USER_BLOCK"."USER_BLOCKER" IS '차단한 사람';

DROP TABLE "REVIEW_DESCRIPTION";

CREATE TABLE "REVIEW_DESCRIPTION" (
	"MANNER_NO"	NUMBER		NOT NULL,
	"MANNER_DESCRIPTION"	VARCHAR2(300)		NOT NULL
);

COMMENT ON COLUMN "REVIEW_DESCRIPTION"."MANNER_NO" IS '매너번호';

COMMENT ON COLUMN "REVIEW_DESCRIPTION"."MANNER_DESCRIPTION" IS '매너설명';

ALTER TABLE "GOODS_SELL" ADD CONSTRAINT "PK_GOODS_SELL" PRIMARY KEY (
	"GOODS_NO"
);

ALTER TABLE "GOODS_IMAGE" ADD CONSTRAINT "PK_GOODS_IMAGE" PRIMARY KEY (
	"IMAGE_NO"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "PK_CHAT_MESSAGE" PRIMARY KEY (
	"MESSAGE_NO"
);

ALTER TABLE "GU_AREA" ADD CONSTRAINT "PK_GU_AREA" PRIMARY KEY (
	"GU_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"RATING_NO"
);

ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "PK_CHAT_ROOM" PRIMARY KEY (
	"CHAT_NO"
);

ALTER TABLE "REVIEW_RATING" ADD CONSTRAINT "PK_REVIEW_RATING" PRIMARY KEY (
	"REVIEW_NO",
	"MANNER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "USER_COMPLAIN" ADD CONSTRAINT "PK_USER_COMPLAIN" PRIMARY KEY (
	"U_COMPLAIN_NO"
);

ALTER TABLE "U_COMPLAIN_CTG_1" ADD CONSTRAINT "PK_U_COMPLAIN_CTG_1" PRIMARY KEY (
	"U_COM1_CTG_NO"
);

ALTER TABLE "U_COMPLAIN_CTG_2" ADD CONSTRAINT "PK_U_COMPLAIN_CTG_2" PRIMARY KEY (
	"U_COM2_CTG_NO"
);

ALTER TABLE "BOARD_COMPLAIN" ADD CONSTRAINT "PK_BOARD_COMPLAIN" PRIMARY KEY (
	"B_COMPLAIN_NO"
);

ALTER TABLE "B_COMPLAIN_CTG_1" ADD CONSTRAINT "PK_B_COMPLAIN_CTG_1" PRIMARY KEY (
	"B_COM1_CTG_NO"
);

ALTER TABLE "B_COMPLAIN_CTG_2" ADD CONSTRAINT "PK_B_COMPLAIN_CTG_2" PRIMARY KEY (
	"B_COM2_CTG_NO"
);

ALTER TABLE "GOODS_LIKE" ADD CONSTRAINT "PK_GOODS_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"GOODS_NO"
);

ALTER TABLE "REQUEST_PAY" ADD CONSTRAINT "PK_REQUEST_PAY" PRIMARY KEY (
	"ORDER_NO"
);

ALTER TABLE "USER_BLOCK" ADD CONSTRAINT "PK_USER_BLOCK" PRIMARY KEY (
	"USER_BLOCKED",
	"USER_BLOCKER"
);

ALTER TABLE "REVIEW_DESCRIPTION" ADD CONSTRAINT "PK_REVIEW_DESCRIPTION" PRIMARY KEY (
	"MANNER_NO"
);

ALTER TABLE "GOODS_SELL" ADD CONSTRAINT "FK_MEMBER_TO_GOODS_SELL_1" FOREIGN KEY (
	"SELLER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "GOODS_SELL" ADD CONSTRAINT "FK_MEMBER_TO_GOODS_SELL_2" FOREIGN KEY (
	"BUYER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "GOODS_SELL" ADD CONSTRAINT "FK_CATEGORY_TO_GOODS_SELL_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "CATEGORY" (
	"CATEGORY_NO"
);

ALTER TABLE "GOODS_IMAGE" ADD CONSTRAINT "FK_GOODS_SELL_TO_GOODS_IMAGE_1" FOREIGN KEY (
	"GOODS_NO"
)
REFERENCES "GOODS_SELL" (
	"GOODS_NO"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "FK_CHAT_ROOM_TO_CHAT_MESSAGE_1" FOREIGN KEY (
	"CHAT_NO"
)
REFERENCES "CHAT_ROOM" (
	"CHAT_NO"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_MESSAGE_1" FOREIGN KEY (
	"SENDER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_2" FOREIGN KEY (
	"RECEIVER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_GOODS_SELL_TO_REVIEW_1" FOREIGN KEY (
	"GOODS_NO"
)
REFERENCES "GOODS_SELL" (
	"GOODS_NO"
);

ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "FK_GOODS_SELL_TO_CHAT_ROOM_1" FOREIGN KEY (
	"GOODS_NO"
)
REFERENCES "GOODS_SELL" (
	"GOODS_NO"
);

ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_ROOM_1" FOREIGN KEY (
	"BUYER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REVIEW_RATING" ADD CONSTRAINT "FK_REVIEW_TO_REVIEW_RATING_1" FOREIGN KEY (
	"REVIEW_NO"
)
REFERENCES "REVIEW" (
	"RATING_NO"
);

ALTER TABLE "REVIEW_RATING" ADD CONSTRAINT "FK_REVIEW_REVIEW_RATING_1" FOREIGN KEY (
	"MANNER_NO"
)
REFERENCES "REVIEW_DESCRIPTION" (
	"MANNER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "USER_COMPLAIN" ADD CONSTRAINT "FK_U_C_CTG_1_TO_USER_C_1" FOREIGN KEY (
	"U_COM1_CTG_NO"
)
REFERENCES "U_COMPLAIN_CTG_1" (
	"U_COM1_CTG_NO"
);

ALTER TABLE "USER_COMPLAIN" ADD CONSTRAINT "FK_U_C_CTG_2_TO_USER_C_1" FOREIGN KEY (
	"U_COM2_CTG_NO"
)
REFERENCES "U_COMPLAIN_CTG_2" (
	"U_COM2_CTG_NO"
);

ALTER TABLE "USER_COMPLAIN" ADD CONSTRAINT "FK_MEMBER_TO_USER_C_1" FOREIGN KEY (
	"U_COMPLAINER"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "USER_COMPLAIN" ADD CONSTRAINT "FK_MEMBER_TO_USER_C_2" FOREIGN KEY (
	"U_COMPLAINED"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "U_COMPLAIN_CTG_2" ADD CONSTRAINT "FK_U_C_CTG_1_TO_U_C_CTG_2_1" FOREIGN KEY (
	"U_COM1_CTG_NO"
)
REFERENCES "U_COMPLAIN_CTG_1" (
	"U_COM1_CTG_NO"
);

ALTER TABLE "BOARD_COMPLAIN" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_C_1" FOREIGN KEY (
	"B_COMPLAINER"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_COMPLAIN" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_C_2" FOREIGN KEY (
	"B_COMPLAINED"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_COMPLAIN" ADD CONSTRAINT "FK_B_C_CTG_1_TO_BOARD_C_1" FOREIGN KEY (
	"B_COM1_CTG_NO"
)
REFERENCES "B_COMPLAIN_CTG_1" (
	"B_COM1_CTG_NO"
);

ALTER TABLE "BOARD_COMPLAIN" ADD CONSTRAINT "FK_B_C_CTG_2_TO_BOARD_C_1" FOREIGN KEY (
	"B_COM2_CTG_NO"
)
REFERENCES "B_COMPLAIN_CTG_2" (
	"B_COM2_CTG_NO"
);

ALTER TABLE "BOARD_COMPLAIN" ADD CONSTRAINT "FK_GOODS_SELL_TO_BOARD_C_1" FOREIGN KEY (
	"GOODS_NO"
)
REFERENCES "GOODS_SELL" (
	"GOODS_NO"
);

ALTER TABLE "B_COMPLAIN_CTG_2" ADD CONSTRAINT "FK_B_C_CTG_1_TO_B_C_CTG_2_1" FOREIGN KEY (
	"B_COM1_CTG_NO"
)
REFERENCES "B_COMPLAIN_CTG_1" (
	"B_COM1_CTG_NO"
);

ALTER TABLE "GOODS_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_GOODS_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "GOODS_LIKE" ADD CONSTRAINT "FK_GOODS_SELL_TO_GOODS_LIKE_1" FOREIGN KEY (
	"GOODS_NO"
)
REFERENCES "GOODS_SELL" (
	"GOODS_NO"
);

ALTER TABLE "REQUEST_PAY" ADD CONSTRAINT "FK_GOODS_SELL_TO_REQUEST_PAY_1" FOREIGN KEY (
	"GOODS_NO"
)
REFERENCES "GOODS_SELL" (
	"GOODS_NO"
);

ALTER TABLE "REQUEST_PAY" ADD CONSTRAINT "FK_MEMBER_TO_REQUEST_PAY_1" FOREIGN KEY (
	"TRADER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "USER_BLOCK" ADD CONSTRAINT "FK_MEMBER_TO_USER_BLOCK_1" FOREIGN KEY (
	"USER_BLOCKER"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "USER_BLOCK" ADD CONSTRAINT "FK_MEMBER_TO_USER_BLOCKED_1" FOREIGN KEY (
	"USER_BLOCKED"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

COMMIT;


CREATE SEQUENCE SEQ_MEMBER_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_GOODS_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_IMAGE_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_RATING_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_MANNER_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_GU_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_B_COM_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_B_COM1_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_B_COM2_NO
	NOCYCLE
	NOCACHE;


CREATE SEQUENCE SEQ_U_COM_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_U_COM1_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_U_COM2_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_ORDER_NO
	NOCYCLE
	NOCACHE;
